language: c

before_install:
  - sudo bash bootstrap.sh
  - n stable

install:
  - npm install

script: 
  - sudo npm test

after_failure:
  - env
  - sudo cat npm-debug.log
  - sudo cat bootstrap.log
  - sudo cat install.log
