language: c

env:
  global:
    - XT_NODE_VERSION=0.8.26
  matrix:
    - XT_PG_VERSION=9.1
    - XT_PG_VERSION=9.3

before_install:
  - sudo -E bash bootstrap.sh --no-installer
  - npm -v
  - node -v

install: npm install

script: npm test

