language: node_js
node_js:
  - "0.8.26"
  - "0.10.26"
env:
  - XT_PG_VERSION="9.1"
  - XT_PG_VERSION="9.3"

before_install:
  - export XT_NODE_VERSION=$TRAVIS_NODE_VERSION
  - sudo -E bash bootstrap.sh --no-installer

install:
  - /usr/local/bin/npm install
  - sudo /usr/local/bin/npm install -g --production

script: /usr/local/bin/npm test

after_failure:
  - cat install.log
