language: node_js
node_js:
  - "0.8.26"
  - "0.10.28"
  - "0.11"

env:
  - XT_PG_VERSION="9.3"

matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.10.28"
    - node_js: "0.11"

before_install:
  - export XT_NODE_VERSION=$TRAVIS_NODE_VERSION
  - sudo -E bash bootstrap/bootstrap.sh --no-installer

install:
  - /usr/local/bin/npm install
  - sudo /usr/local/bin/npm install -g --production

script: /usr/local/bin/npm test

after_failure:
  - env
  - cat install.log
  - cat /etc/postgresql/$XT_PG_VERSION/xtmocha/postgresql.conf
  - cat /etc/postgresql/$XT_PG_VERSION/xtmocha/pg_hba.conf
  - cat /etc/xtuple/4.4.0/xtmocha/config.js
