language: c

before_install:
  - mv ~/.nvm ~/.nvm.disabled
  - sudo bash bootstrap.sh
  - n stable

install:
  - npm install nde -g
  - nde install
  - npm install -g

script:
  - sudo npm test xtuple-server-lib
  - sudo npm test

after_failure:
  - env
  - cat npm-debug.log
  - cat bootstrap.log
  - cat install.log
  - cat node_modules/xtuple/node-datasource/config.js
  - cat node_modules/xtuple/test/lib/login_data.json
  - cat node_modules/xtuple/package.json
  - ls -l node_modules/xtuple/lib
  - ls -l node_modules/xtuple/enyo-client/application
  - ls -l node_modules/xtuple/enyo-client/application/build
  - ./node_modules/xtuple/enyo-client/application/tools/deploy.sh
