language: node_js
node_js:
  - 0.8
  - 0.10
env:
  - XT_PG_VERSION=9.1
  - XT_PG_VERSION=9.2
  - XT_PG_VERSION=9.3
matrix:
  exclude:
    - node_js: 0.8
      env: XT_PG_VERSION=9.3
    - node_js: 0.8
      env: XT_PG_VERSION=9.2

before_install:
  - sudo apt-get purge postgres*
  - sudo -E bash bootstrap.sh --no-installer
  - echo $node_js
  - env

# travis-ci tries to be way too helpful with their node setup
install: /usr/bin/npm install

script: /usr/bin/npm test

after_failure:
  - cat install.log
  - cat /var/log/postgresql/$XT_PG_VERSION/xtmocha
  - cat /var/log/nginx/error.log
  - cat /var/log/xtuple/*
