language: node_js
node_js:
  - 0.8
  - 0.10

addons:
  postgresql: 9.1
  postgresql: 9.3

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential cups libssl-dev
  - sudo apt-get install postgresql-9.1-plv8 postgresql-9.1-plv8

script:
  - sudo npm test
