language: c

env:
  - NODE_VERSION=0.8.26
  - NODE_VERSION=0.10.29

before_install:
- mv ~/.nvm ~/.nvm.disabled
- sudo bash bootstrap.sh
- n stable

install:
- npm install nde -g
- nde install
- npm install -g

script:
- sudo npm test xtuple-server-lib
- sudo npm test

after_failure:
- pg_lsclusters 
- env
- cat npm-debug.log
- cat xtuple-server.log

deploy:
  provider: npm
  email: me@traviswebb.com
  api_key:
    secure: KA7yjcLWyKYTNExDcp6RJsik8wna6qCvsP7ZbZPfSZEucgYWAPN65sIcdF6DMrZHYWp3Z6Cu7gXAuduxP21uFGX7YvkTmOKbyEZHrLd5vG8godt+VZceXtPA8LA75M55bU1NHuzRjKc+ogP1Y50FwQ3Z0EsEpVeCNGphZ3J16w0=
  on:
    tags: true
    repo: xtuple/xtuple-server
    branch: master
