language: c

before_install:
  - rm -rf ~/.nvm
  - sudo bash bootstrap.sh

install:
  - n 0.11
  - npm install
  - npm install -g
  - npm run setup-dev

script:
  - sudo npm test xtuple-server-lib
  - sudo npm test

after_failure:
  - pg_lsclusters 
  - cat npm-debug.log
  - cat xtuple-server-test.log

before_deploy:
  - npm install -g npm
  - git clean -fxd

deploy:
  provider: npm
  email: me@traviswebb.com
  api_key:
    secure: "f3cYn87EJeSHSPU6hiM0fnWDAZap72sxNdJkgQtyVsODshsUpxl/oj9uzpFeq4ftRp1nUOJJE/g55g3KdBVsSEaBfxe0i5hGQb8RAnqmX7DtnmrERDl4oO+3yc/thxjim+CKxg9k9pP7EeE5nyVUSk4gZEaO3cT3I2bXXKAUESc="
  on:
    tags: true
    repo: xtuple/xtuple-server
    all_branches: true
