before_install:
  - rm -rf ~/.nvm
  - sudo bash bootstrap.sh

install:
  - npm install

script: 
  - sudo npm test

after_failure:
  - sudo cat npm-debug.log
  - sudo cat bootstrap.log
  - sudo cat install.log
