language: node_js
node_js:
  - "0.10.28"

env:
  - XT_PG_VERSION="9.3"

matrix:
  fast_finish: true
  #allow_failures:
  #- node_js: "0.11"

before_install:
  - sudo bash bootstrap.sh
  - git clone git@github.com:xtuple/xtuple.git --recursive 
  - sudo rm -rf ~/.npm ~/tmp ~/.nvm

install:
  - /usr/local/bin/npm install

script: 
  - sudo /usr/local/bin/npm test

after_failure:
  - sudo cat npm-debug.log
  - sudo cat bootstrap.log
  - sudo cat install.log
