language: c

env:
  - NODE_VERSION=0.8.26
  - NODE_VERSION=0.10.29

matrix:
  allow_failures:
    - env: NODE_VERSION=0.8.26

before_install:
  - rm -rf ~/.nvm
  - sudo bash bootstrap.sh

install:
  - n 0.11
  - npm install
  - npm install -g
  - npm run setup-dev

script:
  - sudo -E npm test xtuple-server-lib
  - sudo -E npm test

after_failure:
  - pg_lsclusters 
  - cat npm-debug.log
  - cat xtuple-server-error.log

deploy:
  provider: npm
  email: me@traviswebb.com
  api_key:
    secure: KA7yjcLWyKYTNExDcp6RJsik8wna6qCvsP7ZbZPfSZEucgYWAPN65sIcdF6DMrZHYWp3Z6Cu7gXAuduxP21uFGX7YvkTmOKbyEZHrLd5vG8godt+VZceXtPA8LA75M55bU1NHuzRjKc+ogP1Y50FwQ3Z0EsEpVeCNGphZ3J16w0=
  on:
    tags: true
    repo: xtuple/xtuple-server
    branch: master
