language: c

before_install:
  - rm -rf ~/.nvm
  - sudo bash bootstrap.sh

install:
  - n 0.11
  - npm install
  - npm install -g
  - npm run setup-dev

script:
  - sudo npm test xtuple-server-lib
  - sudo npm test

after_failure:
  - pg_lsclusters 
  - cat npm-debug.log
  - cat xtuple-server-test.log

deploy:
  provider: npm
  email: me@traviswebb.com
  api_key:
    secure: "BPZ1otwqkqaIUNcwXNOzl9VFkSv8ipPaFNVYj2RK28DlnxL80OOAfB/VWrSZ/9dR5wlkwk9oX1O/5Uo2cY4Nvq6ctmsleL/hasRTIUkveUaSvZaaRECo0c32fT4C1IJpWSG07zTxGyCs+kNBcaBJInYAE9ARMD5SDH52tnKwWTA="
  on:
    tags: true
    repo: xtuple/xtuple-server
    all_branches: true
