language: node_js
node_js:
  - "0.8.26"
  - "0.10.26"
env:
  - XT_PG_VERSION="9.1"
  - XT_PG_VERSION="9.2"
  - XT_PG_VERSION="9.3"
matrix:
  exclude:
  - node_js: "0.8.26"
    env: XT_PG_VERSION="9.3"
  - node_js: "0.8.26"
    env: XT_PG_VERSION="9.2"

before_install:
- export XT_NODE_VERSION=$TRAVIS_NODE_VERSION
- sudo apt-get purge postgres*
- sudo -E bash bootstrap.sh --no-installer

install: /usr/bin/npm install
script: /usr/bin/npm test

after_failure:
- cat install.log
- cat /var/log/postgresql/$XT_PG_VERSION/xtmocha
- cat /var/log/nginx/error.log
- cat /var/log/xtuple/*

deploy:
  provider: openshift
  user: tjwebb
  password:
    secure: N0m1OybW4S2rm8Ti8XxMnOa8uAcJo7ciV7Do+PUR6pNbzfCo12xzoC0D6aCFGXfKVC/XsNFinlzeIzjX1vnta28zNTySmnqoBb4LBeXtNClzyNDqUqYjZbxYncL+P9Sou+r8GkeVrppmW2EKnUm9TpQaOFODXSzBnOz3ZD5Z6C8=
  app: xtuplescripts
  domain: xtupledev
  on:
    repo: tjwebb/xtuple-scripts
    branch: 4_4_x
