language: node_js
node_js:
  - "0.8.26"
  - "0.10.26"
env:
  - XT_PG_VERSION="9.1"
  - XT_PG_VERSION="9.2"
  - XT_PG_VERSION="9.3"
matrix:
  exclude:
  - node_js: "0.8.26"
    env: XT_PG_VERSION="9.3"
  - node_js: "0.8.26"
    env: XT_PG_VERSION="9.2"

before_install:
  - ipcs -l
  - export XT_NODE_VERSION=$TRAVIS_NODE_VERSION
  - sudo apt-get purge postgres*
  - sudo -E bash bootstrap.sh --no-installer

install: /usr/bin/npm install
script: /usr/bin/npm test

after_failure:
  - cat install.log
  - cat /var/log/postgresql/$XT_PG_VERSION/xtmocha
  - cat /var/log/nginx/error.log
  - cat /var/log/xtuple/*
