language: c

env:
  matrix:
    - XT_PG_VERSION=9.1 XT_NODE_VERSION=0.8.26
    - XT_PG_VERSION=9.1 XT_NODE_VERSION=0.10.26
    - XT_PG_VERSION=9.3 XT_NODE_VERSION=0.10.26
    - XT_PG_VERSION=9.3 XT_NODE_VERSION=0.8.26

before_install:
  - sudo -E bash bootstrap.sh --no-installer

# travis-ci tries to be way too helpful with their node setup
install: /usr/bin/npm install

script: /usr/bin/npm test

